### ISSUE TITLE
how can i fix this when the team magma battle in meteor falls it just breaks

### ISSUE THREAD

**Issue by blazingcody0707** [ryndrb/delta-em#1] opened 2024-08-02 16:11 UTC
### Description

it just crashes when i enter the battle

### Version

master (default, unreleased bugfixes)

**Comment by ryndrb** [comment] 2024-08-02 23:15
Keep in mind that this repo is in progress and there will be plenty of bugs. For the most part, ORAS versions of scripts are mostly done, but I have not play tested them yet (relative to upstream changes); this was the bulk of the current changes in this repo. This will be done once I finish updating wild encounters and trainer parties.

Regarding this issue, it was caused by a change in the way battle partners were handled. When I merged whichever expansion changed, I didn't update the partner battles (Rival Meteor, Steven Mossdeep/Southern Island).

Fixed: d65f17f94227f568ab45edc278b282692af86209

**Closed as completed** 2024-08-04 18:27 UTC
Labels: bug
